# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pr:
 branches:
   include:
    - mfcapps

trigger:
  branches:
    include:
    - main
    - mfcapps
  paths:
    include:
    - src/mfcapps
    exclude:
    - src/*
    - .azurepipelines/*
    - .gitignore
    - LICENSE
    - README.md
pool:
  vmImage: windows-latest

strategy:
 matrix:
   x64: 
     BuildPlatform: 'x64'
     BuildConfiguration: 'Release'
   x86:
     BuildPlatform: 'x86'
     BuildConfiguration: 'Release'
   Arm64:
     BuildPlatform: 'Arm64'
     BuildConfiguration: 'Release'
   
steps:
- task: VSBuild@1
  inputs:
    solution: '$(Build.SourcesDirectory)/src/mfcapps/mfcsampleapp.sln'
    configuration: '$(BuildConfiguration)'
    platform: '$(BuildPlatform)'
    clean: true
    maximumCpuCount: true
    msbuildArchitecture: 'x64'